name: "Build all images"
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build_all_images:
    environment: docker
    runs-on: ubuntu-22.04
    name: "Build docker images"
    steps:
      - name: "Checkout git"
        uses: actions/checkout@v4.2.2
      - name: "Build All images"
        run: go run build_all_images.go
      - name: "Authorize to docker hub"
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ziemniakoss --password-stdin
      - name: "Push tags to docker"
        run: docker push -a ziemniakoss/prettier-apex-server
